// Copyright (c) 2026 sfw contributors. All rights reserved.

#ifndef HAL_STM32_DIO_DIGITAL_OUTPUT_HPP
#define HAL_STM32_DIO_DIGITAL_OUTPUT_HPP

#include <cstdint>

#include "hal_interface/digital_output.hpp"
#include "main.h"

namespace sfw::hal_stm32 {

/**
 * @brief STM32CubeMX-backed implementation of the hal_interface::DigitalOutput
 * interface.
 *
 * This adapter expects CubeMX-generated initialization to configure the pin as
 * an output before Initialize() is called. The class only drives the pin using
 * STM32 HAL GPIO calls and keeps a cached copy of the current logical state.
 *
 * Typical usage:
 * 1. Configure the pin as an output in STM32CubeMX and generate code.
 * 2. Ensure the generated startup path calls MX_GPIO_Init().
 * 3. Construct DigitalOutput with the generated GPIO port and pin constants.
 * 4. Call Initialize() once after CubeMX initialization has completed.
 * 5. Call Write() or Toggle() as needed.
 * 6. Call Deinitialize() when the line is no longer needed.
 */
class DigitalOutput final : public hal_interface::DigitalOutput {
 public:
  /**
   * @brief Constructs an STM32 digital output adapter.
   *
   * The provided GPIO port and pin must refer to a line already configured as
   * an output by CubeMX-generated initialization code.
   *
   * @param[in] gpio_port GPIO port instance generated by STM32CubeMX.
   * @param[in] gpio_pin GPIO pin number (valid range is dependent on the
   * specific STM32 series).
   * @param[in] initial_state Initial logical level to restore on
   * deinitialization.
   */
  explicit DigitalOutput(GPIO_TypeDef* gpio_port, uint16_t gpio_pin,
                         bool initial_state);

  /**
   * @brief Destructor
   */
  ~DigitalOutput() override = default;

  DigitalOutput(const DigitalOutput&) = delete;
  DigitalOutput& operator=(const DigitalOutput&) = delete;
  DigitalOutput(DigitalOutput&&) = delete;
  DigitalOutput& operator=(DigitalOutput&&) = delete;

  /**
   * @brief Marks the GPIO as ready for use and restores its initial state.
   *
   * Expected behavior: concrete STM32 projects must call the CubeMX-generated
   * GPIO initialization before this method. This method must not attempt to
   * reconfigure the pin mode because that configuration belongs to the
   * generated CubeMX project.
   *
   * Call dependencies: MX_GPIO_Init() must have completed before calling this
   * method.
   *
   * @retval ErrorCode::kOk GPIO is ready for output operations.
   * @retval ErrorCode::kInvalidArgument The GPIO port or pin is invalid.
   */
  hal_interface::ErrorCode Initialize() override;

  /**
   * @brief Restores the initial output level and marks the GPIO unused.
   *
   * @retval ErrorCode::kOk The adapter was deinitialized successfully.
   */
  hal_interface::ErrorCode Deinitialize() override;

  /**
   * @brief Returns whether Initialize() completed successfully.
   *
   * @retval true The adapter is initialized.
   * @retval false The adapter is not initialized.
   */
  bool IsInitialized() override;

  /**
   * @brief Drives the configured GPIO to the requested logical level.
   *
   * @param[in] state Desired logical level.
   * @param[in] timeout_ms Unused in this implementation.
   * @retval ErrorCode::kOk GPIO state was updated.
   * @retval ErrorCode::kError Initialize() has not completed.
   */
  hal_interface::ErrorCode Write(bool state, uint32_t timeout_ms) override;

  /**
   * @brief Toggles the configured GPIO output.
   *
   * @param[in] timeout_ms Unused in this implementation.
   * @retval ErrorCode::kOk GPIO state was toggled.
   * @retval ErrorCode::kError Initialize() has not completed.
   */
  hal_interface::ErrorCode Toggle(uint32_t timeout_ms) override;

 private:
  GPIO_TypeDef* gpio_port_{nullptr};
  uint16_t gpio_pin_{0U};
  bool initial_state_{false};
  bool initialized_{false};
  bool state_{false};
};

}  // namespace sfw::hal_stm32

#endif  // HAL_STM32_DIO_DIGITAL_OUTPUT_HPP