
function(sfw_detect_stm32_openocd_target_cfg stm32_defines out_script)
	set(SFW_STM32_OPENOCD_TARGET_CFG "" CACHE STRING
		"Optional override for OpenOCD target cfg, e.g. stm32f4x.cfg")

	if(NOT SFW_STM32_OPENOCD_TARGET_CFG STREQUAL "")
		set(${out_script} "source [find target/${SFW_STM32_OPENOCD_TARGET_CFG}]"
				PARENT_SCOPE)
		return()
	endif()

	set(DetectedStm32Define "")
	foreach(DefineCandidate ${stm32_defines})
		if(DefineCandidate MATCHES "^STM32")
			set(DetectedStm32Define "${DefineCandidate}")
			break()
		endif()
	endforeach()

	if(DetectedStm32Define STREQUAL "")
		message(FATAL_ERROR
			"Unable to detect STM32 define from CubeMX definitions: ${stm32_defines}")
	endif()

	string(REGEX REPLACE "^STM32([A-Z])[0-9].*" "\\1"
		Stm32SeriesLetter "${DetectedStm32Define}")
	string(REGEX REPLACE "^STM32[A-Z]([0-9]).*" "\\1"
		Stm32SeriesDigit "${DetectedStm32Define}")

	set(OpenOcdTargetCfg "")
	if(Stm32SeriesLetter STREQUAL "C")
		set(OpenOcdTargetCfg "stm32c0x.cfg")
	elseif(Stm32SeriesLetter STREQUAL "F")
		set(OpenOcdTargetCfg "stm32f${Stm32SeriesDigit}x.cfg")
	elseif(Stm32SeriesLetter STREQUAL "G")
		set(OpenOcdTargetCfg "stm32g${Stm32SeriesDigit}x.cfg")
	elseif(Stm32SeriesLetter STREQUAL "H" AND Stm32SeriesDigit STREQUAL "7")
		set(OpenOcdTargetCfg "stm32h7x.cfg")
	elseif(Stm32SeriesLetter STREQUAL "L")
		if(Stm32SeriesDigit STREQUAL "0")
			set(OpenOcdTargetCfg "stm32l0.cfg")
		elseif(Stm32SeriesDigit STREQUAL "1")
			set(OpenOcdTargetCfg "stm32l1.cfg")
		elseif(Stm32SeriesDigit STREQUAL "4")
			set(OpenOcdTargetCfg "stm32l4x.cfg")
		elseif(Stm32SeriesDigit STREQUAL "5")
			set(OpenOcdTargetCfg "stm32l5x.cfg")
		endif()
	elseif(Stm32SeriesLetter STREQUAL "U" AND Stm32SeriesDigit STREQUAL "5")
		set(OpenOcdTargetCfg "stm32u5x.cfg")
	elseif(Stm32SeriesLetter STREQUAL "W")
		if(DetectedStm32Define MATCHES "^STM32WBA")
			set(OpenOcdTargetCfg "stm32wbax.cfg")
		elseif(DetectedStm32Define MATCHES "^STM32WB")
			set(OpenOcdTargetCfg "stm32wbx.cfg")
		elseif(DetectedStm32Define MATCHES "^STM32WL")
			set(OpenOcdTargetCfg "stm32wlx.cfg")
		endif()
	endif()

	if(NOT OpenOcdTargetCfg STREQUAL "")
		set(${out_script} "source [find target/${OpenOcdTargetCfg}]" PARENT_SCOPE)
		return()
	endif()

	if(Stm32SeriesLetter STREQUAL "H" AND Stm32SeriesDigit STREQUAL "5")
		set(${out_script}
"source [find target/swj-dp.tcl]\nsource [find mem_helper.tcl]\nif { [info exists CHIPNAME] } {\n  set _CHIPNAME $CHIPNAME\n} elseif { ![info exists _CHIPNAME] } {\n  set _CHIPNAME stm32h5x\n}\nif { ![info exists CPUTAPID] } {\n  set CPUTAPID 0x6ba02477\n}\nsource [find target/stm32x5x_common.cfg]"
			PARENT_SCOPE)
		return()
	endif()

	message(FATAL_ERROR
		"No OpenOCD target mapping for ${DetectedStm32Define}. "
		"Set SFW_STM32_OPENOCD_TARGET_CFG to override.")
endfunction()

function(sfw_apply_platform_preproject_configuration)
	if(SFW_PLATFORM STREQUAL "Linux")
		add_compile_options(-Werror -Wall -Wextra)
		return()
	endif()

	if(SFW_PLATFORM STREQUAL "STM32")
    set(SFW_STM32_PART_NUMBER "" CACHE STRING
      "STM32 part number, for example STM32F401CCTx")
    set(SFW_STM32_CUBEMX_DIR "" CACHE PATH
    "Path to a CubeMX generated project used by STM32 builds")
    include(${CMAKE_SOURCE_DIR}/cmake/AddStm32FirmwareTargets.cmake)
		include(${CMAKE_SOURCE_DIR}/cmake/DetectCubeMxConfig.cmake)
		sfw_detect_cubemx_toolchain(
			"${SFW_STM32_CUBEMX_DIR}"
			SFW_STM32_DEFINES
			SFW_STM32_CPU
			SFW_STM32_FPU
			SFW_STM32_FLOAT_ABI)

    sfw_detect_stm32_openocd_target_cfg(
      "${SFW_STM32_DEFINES}"
      SFW_STM32_OPENOCD_TARGET_SCRIPT)
    file(WRITE
      "${CMAKE_BINARY_DIR}/openocd-target.auto.cfg"
      "# Auto-generated by CMake for STM32 target selection.\n${SFW_STM32_OPENOCD_TARGET_SCRIPT}\n")

		set(SFW_STM32_DEFINES "${SFW_STM32_DEFINES}" PARENT_SCOPE)
		set(SFW_STM32_CPU "${SFW_STM32_CPU}" PARENT_SCOPE)
		set(SFW_STM32_FPU "${SFW_STM32_FPU}" PARENT_SCOPE)
		set(SFW_STM32_FLOAT_ABI "${SFW_STM32_FLOAT_ABI}" PARENT_SCOPE)
		set(SFW_STM32_OPENOCD_TARGET_SCRIPT
      "${SFW_STM32_OPENOCD_TARGET_SCRIPT}" PARENT_SCOPE)
		return()
	endif()

	message(FATAL_ERROR "Unsupported SFW_PLATFORM: ${SFW_PLATFORM}")
endfunction()